version: "3.9"

services:
  nuxt:
    container_name: nuxt
    build: docker/nuxt
    volumes:
      - ./src:/src:cached
      # - nuxt_node_modules:/src/node_modules
    ports:
      - "80:3000"
      - "24678:24678"
    tty: true
    environment:
      - host=0.0.0.0
      - port=80
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "yarn && yarn dev"
# volumes:
#   nuxt_node_modules:
